version: "3.8"
services:
  advertising-rabbitmq:
    image: rabbitmq:3-management
    container_name: advertising-rabbitmq
    hostname: advertising-rabbitmq
    labels:
      NAME: advertising-rabbitmq
    environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: 1234567890
    ports: 
       - 5672:5672
       - 15672:15672
    networks:
      - advertising-localhost
    restart: always

  advertising-postgresql:
    container_name: advertising-postgresql
    image: postgres:latest
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=1234567890
      - PGDATA = /data/postgres
    volumes:
      - advertising-postgresql:/data/postgres
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      - advertising-localhost
    restart: always

  advertising-pgadmin:
    container_name: advertising-pgadmin
    image: dpage/pgadmin4        
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234567890
    networks:
      - advertising-localhost
    restart: always

  advertising-api:
    container_name: advertising-api
    image: advertising-api
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - 12001:5000
    links:
      - advertising-postgresql
    depends_on:
      - "advertising-postgresql"
    networks:
      - advertising-localhost
    restart: always

volumes:
    advertising-postgresql:
        external: true

networks:
  advertising-localhost:
    driver: bridge